# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
 default: &default
   adapter: mysql2
   encoding: utf8
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
   username: root
   password:
   host: localhost

 development:
   <<: *default
   database: like_shop_app_development

 test:
   <<: *default
   database: like_shop_app_test

 production:
   <<: *default
   database: like_shop_app_production
   username: root
   password: 