default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: like_shop_app_development

test:
  <<: *default
  database: like_shop_app_test

production:
  <<: *default
  database: like_shop_production
  username: root 
　password:  

production:
  <<: *default
  database: like_shop_app_production
  username: root
  password: 
